### ISSUE TITLE
dextr.pt file not found

### ISSUE THREAD

**Issue by mspvirajpatel** [weirme/vos_ios#1]

**Comment by weirme** [comment]
You can download it from [here](https://drive.google.com/file/d/1-ojWGRaxsbngPT2cUEUEE1yMSZZgpKkp/view?usp=sharing). This file is the pretrained object segmentation model, and is only used in the first step shown in demo. The following VOS part runs on the server, you may need to choose a VOS model and implement the backend by yourself :)
